version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
      optimus:
        patterns:
          - '@openng/*'
      ngrx:
        patterns:
          - '@ngrx/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
